version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ${PROJECT_DIRECTORY}:${WORKING_DIRECTORY}
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
    environment:
      - PHP_FPM_PORT=${PHP_FPM_PORT}
    depends_on:
      - fpm

  fpm:
    build:
      context: php${PHP_VERSION}/fpm
      args:
        PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
    ports:
      - 9000
    volumes:
      - ${PROJECT_DIRECTORY}:${WORKING_DIRECTORY}
      - ${PROJECT_DIRECTORY}/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb

  cli:
    build:
      context: php${PHP_VERSION}/cli
      args:
        PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
    working_dir: ${WORKING_DIRECTORY}
    volumes:
      - ${PROJECT_DIRECTORY}:${WORKING_DIRECTORY}
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    ports:
      - 3306
    volumes:
      - ${MARIADB_VOLUME_MOUNT}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE_NAME}
      - TERM=meh

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
    links:
      - mariadb
    ports:
      - ${PHPMYADMIN_PORT}:80
  
  # composer:   
  #   image: "composer"
  #   volumes:
  #     - "./web/app:/app"
  #   command: install

